
title: Boris Jamot's Blog
name: Boris Jamot | Awesome Dev
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog, mainly focused on dev topics (PHP, Golang, productivity, quality and so on)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mamyn0va
#permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
theme: minima
#remote_theme: pietromenna/jekyll-cayman-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
