title: Boris Jamot's Blog
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog, mainly focused on dev topics (PHP, Golang, productivity, quality...).
  You can find all my posts (and others) on <a href="https://dev.to/biros" target="_blank"><i class="fab fa-dev"></i></a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
redirect_url: "https://mamyn0va.github.io"
github_username:  mamyn0va
permalink: /:year/:month/:day/:title
disqus:
    shortname: mamyn0va.github.io
dolomonurl: https://framaclic.org/h/my-blog-

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-slate
#remote_theme: pietromenna/jekyll-cayman-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
